### ISSUE TITLE
I successfully installed Mitsuba3,but something went wrong while I was running it

### ISSUE THREAD

**Issue by pekCs** [rgl-epfl/unbiased-inverse-volume-rendering#1]
The error occurs  load_scnce in optimize.py. The report shows"Error while loading "D:\unbiased-inverse-volume-rendering\scenes\janga-smoke\janga-smoke.xml" (near line 19, col 10): unreferenced property "["fixed_max"]" in volume plugin of type "gridvolume"".How can I solve this problem?I'd really appreciate it if you could help me.

**Comment by merlinND** [comment]
Hello @pekCs,

Have you followed the [Getting started](https://github.com/rgl-epfl/unbiased-inverse-volume-rendering#getting-started) instructions from the README?
In particular, please make sure that you are using the `unbiased-inverse-volume-rendering` branch of Mitsuba 3, build it locally, and make sure that version is picked up by your Python interpreter.

**Comment by pekCs** [comment]
Thank you for your reply.But I have a new problem.I have try to compile Mitsuba3 with Clang-12.It told me libc++ was not available,but I have installed libc++ and libc++abi successfully.The specific error is as follows.

```
CMake Error at ext/drjit/ext/drjit-core/ext/nanothread/ext/cmake-defaults/CMakeLists.txt:194 (message):
  When Clang is used to compile Mitsuba, libc++ must be available -- GCC's
  libstdc++ is not supported! (please install the libc++ development headers,
  provided e.g.  by the packages 'libc++-dev' and 'libc++abi-dev' on
  Debian/Ubuntu).
Call Stack (most recent call first):
  CMakeLists.txt:75 (include)
```

These are my versions:
Ubuntu 22.04.2 LTS
Clang 12.0.0

I have compiled with Clang14,but there was a mistake.It told me libpng.conf having an error.Can I compile Mitsuba3 with Clang14?

**Comment by merlinND** [comment]
It might be that the `libc++` version you installed was not for the right Clang version?
E.g. for Clang 15 you could do:

```
sudo apt install clang-15 libc++-15-dev libc++abi-15-dev
cd mitsuba3
mkdir build && cd build
CC=clang-15 CXX=clang++-15 cmake -GNinja .. 
ninja
```

**Comment by pekCs** [comment]
I'm sorry to waste your time.But when I  complied my mitsuba3,it told me a new problem.he specific error is as follows.

 `FAILED:` ext/libpng/pnglibconf.c /home/user/mitsuba3/build/ext/libpng/pnglibconf.c 
cd /home/user/mitsuba3/build/ext/libpng && /home/user/miniconda3/lib/python3.10/site-packages/cmake/data/bin/cmake -DOUTPUT=pnglibconf.c -P /home/user/mitsuba3/build/ext/libpng/scripts/gensrc.cmake
options.awk: bad line (10): com
CMake Error at scripts/gensrc.cmake:68 (message):
  Failed to generate `pnglibconf.tf5`

I think I have downloaded the whole libpng.How do I solve this problem?

**Comment by merlinND** [comment]
I see that this error seems related to Awk and line-endings: https://stackoverflow.com/a/66497823/3792942
By any chance did you clone the repo on Windows and then try to build it on Linux / WSL?

A quick fix to try would be to edit `mitsuba3/ext/libpng/scripts/options.awk` to use LF (Unix-styl line endings) instead of CRLF (Windows-style line endings).
If you use VS Code, there's a small button at the bottom right of the window to make this change (you can see that my file uses LF already):

![image](https://github.com/rgl-epfl/unbiased-inverse-volume-rendering/assets/5563370/cc4be4a6-5151-451b-b3e6-d34e5cdc383a)

**Comment by pekCs** [comment]
I compile on Windows successfully,thank you for your replies.

**Comment by pekCs** [comment]
Unfortunately，I can successfully render hello.xml by command line.But I can't import mitsuba,by the way,`setpath.bat` is located in 'build/resources',Where's correct location?And if I want to use 'import mitsuba' in Vscode,what am I supposed to do?

**Comment by merlinND** [comment]
Have a look at the documentation about `setpath`:

https://mitsuba.readthedocs.io/en/stable/src/developer_guide/compiling.html#running-mitsuba

**Comment by ghost** [comment]
@pekCs Sorry to bother you! How did you successfully execute "git clone --recursive https://github.com/mitsuba-renderer/mitsuba3 --branch unbiased-inverse-volume-rendering"? I always get an error when executing this statement.

**Comment by merlinND** [comment]
Hello @WhyICanNotDo,

I just tested the command and it ran succesfully. What error are you encountering?
