### ISSUE TITLE
Project page is invalid

### ISSUE THREAD

**Issue by ghost** [rgl-epfl/unbiased-inverse-volume-rendering#3]
I apologize for the inconvenience, but the link to the project page you provided is no longer valid, so I am unable to download the relevant data. Could you please update the link?

**Comment by merlinND** [comment]
Hello @WhyICanNotDo,

I just tested the link and it works for me: https://rgl.epfl.ch/publications/NimierDavid2022Unbiased/
Perhaps the website was down temporarily?

**Comment by WhyICanNotDo** [comment]
Thank you very much for your prompt reply! I don't know the reason, I have tried many methods but I still can't download the "scene data", can you send the "scene data" to me directly by email? Thank you very very much!

**Comment by merlinND** [comment]
Does this direct link work?
http://rgl.s3.eu-central-1.amazonaws.com/media/papers/NimierDavid2022Unbiased.zip

**Comment by ghost** [comment]
Sorry to bother you again, I just sent a message to your gmail mailbox, I hope it will take a little time for you to send me the dataset by email. Thank you very very much!

**Comment by ghost** [comment]
I'm very sorry, your latest link is working (it is my improper operation that caused the download to fail)! Thank you for your prompt reply. Thank you very very much!

**Comment by merlinND** [comment]
No worries, I'm glad it worked!
